<?php
/**
 * how_to_improve_visits.phtml
 * 
 * E-mail explicando ao usuário como melhorar visitas.
 * 
 * @author Mauro Ribeiro
 * @since 2011-03-05
 */

/* Caminho da função de autoLogin, links e tag */
require_once APPLICATION_PATH."/views/helpers/Access.php";
$url = 'http://blog.empreendemia.com.br/2012/02/02/como-melhorar-as-visitas-da-sua-pagina/';
$utm = '?utm_source=lifecycle&utm_medium=email&utm_campaign='.urlencode('dicas para melhorar visitas');
?>

<p>Oi, <?php echo $this->user->name ?>. Tudo bem?</p>

<p>Queremos melhorar o número de visitas que você recebe na sua página. Para isso, selecionamos algumas dicas de como vender mais, usando o Empreendemia.</p>

<p>Para conferir como aumentar suas vendas, clique <a href="<?php echo $url.$utm ?>">aqui</a>.</p>

<p>
Grande abraço,<br /> <br />

Gabriel<br />
(Torcendo para uma multidão de pessoas visitar a sua página)
</p>

<div style="font-family:Verdana,sans-serif;color:#666;text-shadow:1px 1px 0 #fff;font-size:10px;border-top:1px dotted #888;margin-top:20px;margin-bottom:20px">
	<div style="margin-top:20px"><a href="http://www.empreendemia.com.br/e/empreendemia/pessoas/19112193" target="_blank"><img style="height:80px;width:80px;float:left" src="http://www.empreendemia.com.br/userfiles/users/19112/19112193f8433c0947e79396cc6e1ceb6dea7ea6b76b3d72/200_5978a89f7b.jpg"></a></div>
	<div style="margin-left:100px;margin-top:20px;color:#0c478b;font-size:20px;font-family:Arial,Helvetica,sans-serif;margin-bottom:2px"><a href="http://www.empreendemia.com.br/e/empreendemia/pessoas/19112193" style="color:#0c478b;text-decoration:none" target="_blank">Gabriel Guerra Costa</a></div>
	<div style="margin-left:100px;font-size:12px;font-family:Arial,Helvetica,sans-serif;font-weight:bold;margin-bottom:8px">Agente infiltrado - Departamento de usuários felizões</div>
	<div style="margin-left:100px;margin-bottom:5px">Escritório: (11) 3230-9233</div>
	<div style="margin-left:100px;margin-bottom:5px">Celular (tim): (19) 8364-9759</div>
	<div style="margin-top:30px;margin-bottom:5px"><a href="http://www.empreendemia.com.br" style="text-decoration:none;color:#666;font-weight:bold" target="_blank"><img src="http://empreendemia.com.br/images/favicon.ico" style="vertical-align:middle"> empreendemia.com.br</a> - a rede de empresas para acelerar seus negócios</div>
	<div style="margin-bottom:20px"><a href="http://www.saiadolugar.com.br" style="text-decoration:none;color:#666;font-weight:bold" target="_blank"><img src="http://www.saiadolugar.com.br/wp-content/themes/saiadolugar4/images/favicon.ico" style="vertical-align:middle"> saiadolugar.com.br</a> - dicas para o empreendedor que não tem tempo a perder</div>
	<div style="color:#888"><span style="font-style:italic">&quot;I'm Batman&quot;</span> - Batman</div>
</div></body></html>
