<?php
/**
 * premium_expiration.phtml
 * Email enviado para dono de empresa que o premium expirou
 * 
 * @author Mauro Ribeiro
 * @since 2011-03-05
 */
?>
<p>Olá <?php echo $this->user->name ?>, tudo bem?</p>

<p>Estou mandando este e-mail porque o seu Premium no Empreendemia está terminando.</p>

<p>Você ficou satisfeito com o serviço?</p>

<p>Caso não tenha tido tempo de usá-lo, me avisa por favor que posso extender o seu prazo e te ajudar na configração do seu perfil.</p>

<p>Abraços,<br />
Lucas Fernandes Hoogerbrugge<br />
Mobile: +55 19 8177 5725<br />
Office: +55 11 3230 9233</p>

<p>Empreendemia<br />
A rede social focada em acelerar negócios entre empresas</p>

<p>Saia do Lugar<br />
Dicas para o empreendedor que não tem tempo a perder</p>