<?php
/**
 * some_indicated_companies_2.phtml
 * 
 * E-mail sugerindo empresas de Assessoria Empresial e Contabilidade para as 
 * empresas de TI e Informática.
 * 
 * @author Lucas Gaspar
 * @since 2012-04-23
 */

/* Caminho da função de autoLogin, links e tag */
require_once APPLICATION_PATH."/views/helpers/Access.php";
$url = 'http://www.empreendemia.com.br/lista-de-empresas/'.$this->user->company->city->region->slug.'/'.$this->user->company->city->slug.'/assessoria-empresarial';
$utm = '?utm_source=lifecycle&utm_medium=email&utm_campaign='.urlencode('indicacao de algumas empresas');
?>

<p>Oi, <?php echo $this->user->name ?>. Tudo bem?</p>

<p>Como você sabe, a maior função do Empreendemia é gerar negócios.</p>

<p>Como você trabalha com TI e Informática, selecionei algumas empresas de assessoria e consultoria empresarial da sua cidade, que poderiam ser seus parceiros.</p>

<p>Para ver essas empresas e já entrar em contato, é só clicar <a href="<?php echo $this->Access()->autoLoginLink($this->user, $url).$utm ?>">aqui</a>.</p>

<p>
Grande abraço,<br /> <br />

Luiz<br />
</p>

<div style="font-family: Verdana,sans-serif;color:#666;text-shadow:1px 1px 0 #fff;font-size:10px;border-top:1px dotted #888;margin-top:20px;margin-bottom:20px;">
	<div style="margin-top:20px;"><a href="http://empreendemia.com.br/userfiles/users/19112/191120113037c3a2ac8be6617870b1ebf189db136892f107/100_657e47319e.png"><img style="height:80px;width:80px;float:left;" src="http://empreendemia.com.br/userfiles/users/19112/191120113037c3a2ac8be6617870b1ebf189db136892f107/100_657e47319e.png" /></a></div>
	<div style="margin-left:100px;margin-top:20px;color:#0C478B;font-size:20px;font-family: Arial,Helvetica,sans-serif;margin-bottom:2px;"><a href="http://empreendemia.com.br/userfiles/users/19112/191120113037c3a2ac8be6617870b1ebf189db136892f107/100_657e47319e.png" style="color:#0C478B;text-decoration:none;">Luiz Piovesana</a></div>
	<div style="margin-left:100px;font-size:12px;font-family: Arial,Helvetica,sans-serif;font-weight:bold;margin-bottom:8px;">Diretor de Criação e Cultivo de Clientes Felizões e Saltitantes</div>
	<div style="margin-left:100px;margin-bottom:5px;">Celular (tim): +55 (19) 9289-0687</div>
	<div style="margin-left:100px;margin-bottom:5px;">Office: +55 (11) 3230-9233</div>
	<div style="margin-top:30px;margin-bottom:5px;"><a href="http://www.empreendemia.com.br" style="text-decoration:none;color:#666;font-weight:bold"><img src="http://empreendemia.com.br/images/favicon.ico" style="vertical-align:middle" /> empreendemia.com.br</a> - a rede de empresas para acelerar seus negócios</div>
	<div style="margin-bottom:20px;"><a href="http://www.saiadolugar.com.br" style="text-decoration:none;color:#666;font-weight:bold"><img src="http://www.saiadolugar.com.br/wp-content/themes/saiadolugar4/images/favicon.ico" style="vertical-align:middle" /> saiadolugar.com.br</a> - dicas para o empreendedor que não tem tempo a perder</div>
	<div style="color:#888;"><span style="font-style:italic;">"Pelos poderes de Grayskull!"</span> - He-man</div>
</div></body></html>
