<?php
/**
 * ads_expirations.phtml
 * Email enviado para sysadmins com lista de anúncios expirados
 * 
 * @author Mauro Ribeiro
 * @since 2011-09-06
 */
?>
<h1>Cron Diário - Expiração de Publicidade</h1>

<p>Campanhas que expiraram hoje:</p>

<?php if ($this->ads) : ?>
<ul>
    <?php foreach ($this->ads as $ad) : ?>
    <li>
        <a href="http://www.empreendemia.com.br/e/<?php echo $ad->product->company->slug ?>/produtos/<?php echo $ad->product->slug ?>" style="font-weight:bold"><?php echo $ad->product->name ?></a>
        <ul>
            <li>id: <?php echo $ad->id ?></li>
            <?php foreach ($ad->product->company->users as $user) : ?>
            <li><a href="http://www.empreendemia.com.br/e/<?php echo $ad->product->company->slug ?>/pessoas/<?php echo $user->id ?>"><?php echo $user->name ?> <?php echo $user->family_name ?></a> - <?php echo $user->login ?></li>
            <?php endforeach ?>
        </ul>
        <br />
    </li>
    <?php endforeach ?>
</ul>
<?php else : ?>
<p>nenhum</p>
<?php endif ?>